= Feasibility Study - Data Availability with Validation on Cardano
Sky Protocol Team
2024-09-27
:doctype: book
:showtitle:

== Overview

This report addresses link:https://milestones.projectcatalyst.io/projects/1200203/milestones/1[milestone 1]
of the link:https://projectcatalyst.io/funds/12/f12-cardano-open-developers/sky-protocol-data-availability-for-cardano-layer-2-solutions[Sky Protocol: Data Availability for Cardano Layer 2 Solutions] proposal.

== Maintenance of Unique Identifiable Contract State

For the maintenance of unique identifiable contract state, we will use
NFT-based oracles, similar to the
link:https://plutus-pioneer-program.readthedocs.io/en/latest/pioneer/week6.html[example]
from the Plutus Pioneer Program.

Each data topic will be associated with an NFT that stores the root
hash as its datum.

Off-chain code will be used to find the NFT UTXO.

== Multisig for Data Availability Committee

Initially, we will use a simple M-of-N multisig based on Ed25519 signatures.

A configurable number of data operators will be required to sign hashes.

In the future we might use Schnorr signatures for reduced size.

== Merkle Proof of Data Availability

We will implement the usual
link:https://pangea.cloud/docs/audit/merkle-trees#understand-membership-proof[Merkle
membership proof] approach in Plutus.

The hashes of the path segments from the root to the leaf node in question
(and of required sibling nodes) are signed.
