port: 8080
tokenName: "SkyBridge"

atlas:
  coreProvider:
    # For Maestro, maestroToken holds the api key and
    # turboSubmit field dictates whether the transactions
    # are to be submitted via their turbo submit endpoint.
    maestroToken: ""
    turboSubmit: false
  # Specifies your network and must be one of
  # mainnet, preprod, preview, testnet (for legacy testnet)
  # & privnet (for local private network).
  networkId: ""
  logging:
    - type:
        tag: "stderr"
      severity: "Debug"
      verbosity: "V2"
  # (Optional) If set to true, operations involving provider
  # are timed and corresponding durations are logged.
  logTiming: false
