name: Contracts Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - uses: actions/setup-node@v4
    - run: ./test-setup.sh
      working-directory: ./contracts/off-chain
