name: Contracts Tests (disabled for now due to Nix dependency problem with cardano-binary package)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix develop .
      working-directory: ./contracts
    - uses: actions/setup-node@v4
    - name: Setup and run tests
      working-directory: ./contracts/off-chain
      run: ./test-setup.sh
