name: Contracts Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  contracts_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - uses: actions/setup-node@v4
    - run: nix develop --accept-flake-config --command ./test-setup.sh
      working-directory: ./contracts/off-chain
  atlas_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
    - run: nix develop --accept-flake-config --command cabal update && cabal test all
      working-directory: ./sky-atlas
